### ISSUE TITLE
Rename time variables to timestamp on VestedPayment contract and tests

### ISSUE THREAD

**Issue by AugustoL** [windingtree/LifToken#160]
We want to rename the variable names to timestamp instead of time, for example: startTime -> startTimestamp

**Comment by kvbik** [comment]
hahaha, the `startTime` is the only one I can find :D

**Comment by kvbik** [comment]
maybe do the same rename for `test/helpers/increaseTime.js` and `test/helpers/latestTime.js`?

**Comment by nberger** [comment]
I'm not crazy about renaming those :)
