### ISSUE TITLE
Resolve all the TODOs in the code

### ISSUE THREAD

**Issue by nberger** [windingtree/LifToken#165]
Go through the code and resolve all the TODOs

**Comment by kvbik** [comment]
resolving the TODOs can be just creation of another issues here, but I agree. the code is not a good issue tracker ;)

**Comment by nberger** [comment]
Sure, they can be moved to issues, but most important they have to be
solved, usually with code/doc changes :)

>

**Comment by AugustoL** [comment]
Last TODO on contracts solved https://github.com/windingtree/LifToken/pull/192
