### ISSUE TITLE
Rename MarketMaker to MVM

### ISSUE THREAD

**Issue by AugustoL** [windingtree/LifToken#174]
We have to rename all mentions of Market Maker to Market Validation Mechanism.

I think the name is too long to use it on a contract, we can name it MVM.sol

**Comment by nberger** [comment]
I think we can use MarketValidationMechanism, it's not many usages, just the file name, the contract name and some calls to constructors, basically that. We can keep mvm to the variable where we assign the constructed thing. What do you think?

**Comment by AugustoL** [comment]
Ok, I agree.

**Comment by nberger** [comment]
Done in #181
