### ISSUE TITLE
transferData: fail when `call` returns false

### ISSUE THREAD

**Issue by nberger** [windingtree/LifToken#184]
`transferData` uses `call` to execute a contract call on transfer. But the `call` return value is being ignored, so if the `call` throws, the `transferData` does not throw. I think that should be avoided: if the `call` fails, the `transferData` should also fail. And this is connected to #183: "fail" currently means that it should throw, but if we change it to return bool instead then fail would mean to return false. In that case we could just return the result from the `call`.

For context, here's the documentation of `call`: https://solidity.readthedocs.io/en/latest/types.html#members-of-addresses

/cc @AugustoL

**Comment by AugustoL** [comment]
thx will look at it tomorrow.

**Comment by AugustoL** [comment]
fixed in #191
