### ISSUE TITLE
Approve command doesn't throw with spender=0x0, but tests expect it to throw

### ISSUE THREAD

**Issue by nberger** [windingtree/LifToken#205]
Example prop-based test that fails: 

```
{commands:
 [
  {"type":"fundCrowdsaleOverSoftCap","account":10,"softCapExcessWei":25,"finalize":true},
  {"type":"approve","lif":23,"fromAccount":0,"spenderAccount":"zero"}],
  crowdsale: {
    rate1: 23, rate2: 16, foundationWallet: 0, 
    setWeiLockSeconds: 1726, owner: 0
}};
```

**Comment by nberger** [comment]
@AugustoL you fixed something in this area recently, do you know what's failing here?

**Comment by AugustoL** [comment]
Yes and here is the issue https://github.com/windingtree/LifToken/blob/master/test/commands.js#L405 missing &
Weird that the linter didnt throw, right?

**Comment by nberger** [comment]
We have to fix that. The linter didn't catch because it's valid code, it's the bitwise. And actually the result might be the same in the end (it yields 0 or 1, which map to false and true in js land, not sure what happens when using it in a assert.equal with false... Anyways, we should change it to `&&`.

But I think something might be still missing in the contract

**Comment by nberger** [comment]
What I think is wrong here is: why are we trying to allow approvals for address 0x0? What's the goal of allowing to approve for that address? Even though in the end it doesn't have any effect, because `transferFrom` I think it can always run with _value=0, without regard to what's approved for the addresses involved, I don't think we need to allow doing an `approve` for address 0x0. I'll send a fix for this test based on this assumption, let's take it from there

**Comment by nberger** [comment]
Sorry, what I wanted to mean is: why do we want to throw when spender=0x0? I'm not sure why someone would like to approve for spender=0x0, but still I'm not sure that we need to validate that. In any case, that validation is missing in the contract, but I think we have to remove the expectation in the test for it to throw, that's what I'm going to change.
