### ISSUE TITLE
Analyze test failure with setWeiPerUSD + fundOverSoftCap example

### ISSUE THREAD

**Issue by nberger** [windingtree/LifToken#214]
failed example:

```
{
  commands: [
    {"type":"setWeiPerUSDinTGE","wei":9999999143274796,"fromAccount":2},
    {"type":"fundCrowdsaleOverSoftCap","account":1,"softCapExcessWei":35,"finalize":true}
  ], 
  crowdsale: {rate1: 33, rate2: 39, foundationWallet: 6, setWeiLockSeconds: 3501, owner: 2}};
```

failed build: https://travis-ci.org/windingtree/LifToken/builds/276964398

**Comment by AugustoL** [comment]
@nberger any update on this?

**Comment by nberger** [comment]
I'll take a look today. At first sight it seems like some issue with the `wei` number, maybe because of too many significant digits combined with not using BigNumber somewhere in the tests. I'll post my findings here.

**Comment by nberger** [comment]
Turns out the bug is a little pesky: it has to do with running the finalizeCrowdsale with this setWeiPerUSD value that has many significate digits (16 I think). But this specific example doesn't fail in master since df4b176 introduced a slight change in the FundCrowdsaleOverSoftCap and such commands so setWeiPerUSD is now reset to 10000 in those commands and the issue with significant digits is gone. The issue has to do with the version of bignumber that we are using (2.0.2) which throws on integers with more than 15 significant digits. Upgrading to versions after 2.2.0 should fix the issue but I was not able to upgrade the library as it's a transitive dependency from web3, etc... (more about the issue in bignumber.js: https://github.com/MikeMcl/bignumber.js/issues/11#issuecomment-195005182)

So...

the thing is that the issue doesn't seem very important, as we are not supposed to have values with 16 significant digits in production... So I propose to cut the digits in the generator and instead of having `wei` there let's have `weiDivided100` and cut 2 digits there, then multiply by 100 in the commands... 14 significant digits is not that bad after all :D

What do you think @AugustoL?
