### ISSUE TITLE
Better error messages on chai.assert 

### ISSUE THREAD

**Issue by AugustoL** [windingtree/LifToken#23]
chai.assert allows the developer to throw a custom message on each condition verification, right now you have to guess where it happens on long test cases, the goal is to add a custom message explaining where and why it fail, this will also make the tests more understandable.

**Comment by nberger** [comment]
This is definitely a great idea and we started doing this in some tests. I think we can close this issue and keep it as a guideline

**Comment by kvbik** [comment]
+1
