### ISSUE TITLE
Crowdsale: use separate address as owner of foundersVestedPayment

### ISSUE THREAD

**Issue by nberger** [windingtree/LifToken#232]
It should be possible (and I think desirable) to use a different address as the foundersVestedPayment owner, separate from the foundationWallet.

Perhaps it could be the same address as the `owner` of the LifCrowdsale, but I'm not sure, maybe it's better to allow passing a separate address in `LifCrowdsale` constructor

What do you think @AugustoL?

**Comment by AugustoL** [comment]
Im going to add another address on the constructor, how should it be called? `foundersWallet`?

**Comment by AugustoL** [comment]
closed in #233
