### ISSUE TITLE
Double Spend issue in approveData

### ISSUE THREAD

**Issue by nberger** [windingtree/LifToken#246]
This attack occurs when a user A approves user B a limit to transfer of X tokens. Then, the same user A wants to approve a Y amount of tokens to user B. If B monitors unmined transactions can quickly create a transaction to spend the X tokens previously approved. If B transaction is mined first, then B would be able to spend Y tokens even though B just spend X. In this example A wanted to change the approved value from X to Y but B can finally spend X+Y. The approveData is not protected against this attack:

```js
function approveData(address spender, uint256 value, bytes data)
  whenNotPaused returns (bool) {
  require(spender != address(this));
  allowed[tx.origin][spender] = value;
  ...
```
This should be modified to

```js
function approveData(address spender, uint256 value, bytes data)
  whenNotPaused returns (bool) {
  require(spender != address(this));
  require((allowed[tx.origin][spender] == 0) || (value == 0));
  allowed[tx.origin][spender] = value;
  ...
```

**Comment by nberger** [comment]
Perhaps we should follow what zeppelin-solidity is doing and not add the validation here. In that case we should also remove it from `approve` (inherited from `StandardToken`): https://github.com/OpenZeppelin/zeppelin-solidity/issues/438

In [this comment] it's explained really well: Basically adding that validation only makes it slightly safer, but still someone could get N+M tokens from Alice (the source account) when Alice wanted to allow just `M` (the scenario is Alice originally approved N but wants to change approval to M, and someone "front runs" the approval change to transfer both N and M, resulting in total of N+M transferred)

@AugustoL thoughts?

**Comment by AugustoL** [comment]
I think if it make it safer we can add it in both methods `approve` and `approveData`

For `approve()` it would look like:
```
function approve(address _spender, uint256 _value) public whenNotPaused returns (bool) {
    require((allowed[msg.sender][_spender] == 0) || (_value == 0));
    return super.approve(_spender, _value);
}
```

**Comment by nberger** [comment]
@AugustoL I was not clear but the correct phrase is "this way is only slightly safer, **if safer at all**", taken from https://github.com/OpenZeppelin/zeppelin-solidity/issues/438#issuecomment-329172399. The idea is to remove the validation from `approve` (it's already in `StandardToken`, so there's no need to add it explicitly in `LifToken`, anyways) and to not add it in `approveData`.

Another important aspect from the issue I linked but that I didn't explain here, is that the validation makes `approve` and `approveData` to violate the ERC20 standard. Let me quote from that issue:

---
Currently, approve method in StandardToken.sol does not allow to set allowance to non-zero value if current allowance is non-zero. This directly violates ERC20 standard that says:

> Allows _spender to withdraw from your account multiple times, up to the _value amount. If this function is called again it overwrites the current allowance with _value.

EIP-20 pull request adds the following to the description of approve method:

> NOTE: To prevent attack vectors like the one described here and discussed here, clients SHOULD make sure to create user interfaces in such a way that they set the allowance first to 0 before setting it to another value for the same spender. THOUGH The contract itself shouldn't enforce it, to allow backwards compatilibilty with contracts deployed before

So current implementation of approve in StandardToken.sol violates EIP-20 as well

---

We could add a comment like the one they added in zeppelin here: https://github.com/OpenZeppelin/zeppelin-solidity/pull/446/files

**Comment by AugustoL** [comment]
Ok, lets add the comment.
