### ISSUE TITLE
Add stateful property-based test

### ISSUE THREAD

**Issue by nberger** [windingtree/LifToken#25]
Use a property-based testing library to generate sequences of transactions , run them and verify invariants/properties that must hold (for example a `submitBid` call should fail if the amount == 0, but it should go through and add the bid to the CrowdsaleStage, except if the token is stopped in which case it should also fail.

The main benefit of this kind of test suite is that the input data has some level of randomness, and also the sequence of commands is arbitrary so we end testing combinations of transactions that we wouldn't have time to write tests for (even if we came up with the same combinations "by hand")

**Comment by AugustoL** [comment]
I like it, maybe we can use http://chancejs.com/ lib.

**Comment by nberger** [comment]
From a quick skimming on changejs, it doesn't look like powerful enough. It's not just to generate some random data (and changejs seems to just generate strings and numbers, but we also need arrays) but also to run the same test with multiple different generated data and once a failure is found, shrink it to a smaller input that still makes the test to fail.

The most promising that I'm aware of in the js world is [jsverify](https://github.com/jsverify/jsverify)
