### ISSUE TITLE
Function finalize() is public and not Ownable

### ISSUE THREAD

**Issue by pabloruiz55** [windingtree/LifToken#296]
I noticed that the function finalize() of LifCrowdsale is marked as public and also it is not Ownable. 
This would allow anyone to finalize the crowdsale (after it hasEnded) and initiate the forwarding of funds.

It doesn't seem to be dangerous, as finalize() doesn't do anything you wouldn't want to do anyways after the crowdsale ended, yet, for some reason you might want to wait some time to finalize() after hasEnded is met, and anyone could just do it for you.

I'd change finalize() so it's Ownable, preventing anyone other than the owner to execute it.

My ETH address, just in case, is 0x263d1C074e6C51f62A1b005c3DE306d68B3Dc13A

**Comment by nberger** [comment]
@pabloruiz55 thanks for looking into this! But we did it this way on purpose, precisely to allow anyone to run the `finalize` tx and thus enable transfers on the tokens as soon as they want to, and to not make it depend on the owners to do it.

We checked very carefully that allowing anyone to run `finalize` would not have unintended effects, and we think everything is lined up that way: funds forwarding, MVM creation, and everything else, it all depends on the state in the contract and doesn't take any input from the message that triggers the transaction.

/cc @AugustoL: I think you will agree with me but I'd like to hear your opinion

**Comment by pabloruiz55** [comment]
Figured so, my only concern is that when you say anyone can trigger it so it doesn't depend on the owners to do it, anyone can also be someone that doesn't have any stakes at all in this. 

If it doesn't have any side effects at all, maybe it is not necessary to change it, but you could also make it so that it checks that the msg.sender at least does have some amount of Lif tokens, making sure he did participate in the crowdsale.

**Comment by AugustoL** [comment]
Thanks @pabloruiz55 for reporting this, but like @nberger said, this is in done in purpose so the lif holders don't need to wait the owner to finish the crowdsale. Like you said too it doesn't have any side effects, is the same for anyone who calls it.

Going to close the issue, but thanks again @pabloruiz55 for reporting it.
