### ISSUE TITLE
Crowdsale locks up if setWeiPerUSDinTGE is not called in time

### ISSUE THREAD

**Issue by adklempner** [windingtree/LifToken#314]
If, for whatever reason, LifCrowdsale.setWeiPerUSDinTGE is not called before `startTimestamp.sub(setWeiLockSeconds)`, it becomes [permanently impossible to buy tokens](https://github.com/windingtree/LifToken/blob/master/contracts/LifCrowdsale.sol#L218).

This can be mitigated by setting `weiPerUSDinTGE` in the constructor, and then changing it later if need be.

**Comment by AugustoL** [comment]
NACK, it will be called by the TGEDeployer contract ! closing it.
