### ISSUE TITLE
Add test case that will show all the token transactions.

### ISSUE THREAD

**Issue by AugustoL** [windingtree/LifToken#4]
Make a test case that will get all the Transfer events on the LifToken contract and show them in order.

Make a test case that will get all the Transfer events of an address on the LifToken contract and show them in order.

**Comment by nberger** [comment]
@AugustoL are we going to do this at some point? I'm not sure how important it is, and if we are not going to implement it, we should close this issue.

**Comment by AugustoL** [comment]
Yes, its not important, closing it.
