### ISSUE TITLE
Check refundable tokens issue

### ISSUE THREAD

**Issue by AugustoL** [windingtree/LifToken#40]
Reference: https://www.reddit.com/r/ethereum/comments/60ql37/attention_be_careful_using_ethereum_tokens/

**Comment by nberger** [comment]
We should add more details about this issue, I'm not sure what is it about exactly

**Comment by nberger** [comment]
@AugustoL: can you add more information here, or close it if it's an issue in the old crowdsale that doesn't exist in the new one, please?

**Comment by nberger** [comment]
@AugustoL I'm closing this issue as it's not clear what the purpose is. Please reopen if you have more information to add.
