### ISSUE TITLE
Add public presale on LifCrowdsale contract and tests for it.

### ISSUE THREAD

**Issue by nberger** [windingtree/LifToken#81]

**Comment by AugustoL** [comment]
We have to add the necessary functions and variables on the LifCrowdsale contract to run a public presale of a maximum amount of tokens before the ICO.

I think that we would need:
* startPresaleBlock & endPresaleBlock.
* maxTokensPresale.
* publicPresaleTokensSold.
* buyPresaleTokens(address beneficiary)
* modify the fallback function to execute the buyPresaleTokens it its between the right blocks.

**Comment by nberger** [comment]
Done in #94
