### ISSUE TITLE
New crowdsale: transfer funds to foundation wallet once minCap was reached

### ISSUE THREAD

**Issue by nberger** [windingtree/LifToken#82]
It's more secure to not keep all the funds in the Crowdsale smart contract. Also notice that since market maker minCap is reached, the extra funds should be forwarded to the market maker contract.

**Comment by AugustoL** [comment]
@nberger are we going to do this? I think we dont need it, on the https://github.com/windingtree/LifToken/pull/136 we distribute the funds once the crowdsale finish on `forwardFunds()`

**Comment by nberger** [comment]
Let's not do it for now, I'm actually not sure how less secure is to just keep the funds in the smart contract until the end of the crowdsale. I'm fine with closing this.
