### ISSUE TITLE
Check totalSupply of tokens in CrowdsaleGenTests

### ISSUE THREAD

**Issue by AugustoL** [windingtree/LifToken#90]
We have the public variable totalSupply on he token contract, this amount should equal : Tokens added on private presale + tokens added on public Presale + tokens sold on the ICO.

**Comment by nberger** [comment]
We also have to check the presale payments, check whether the contract is registering the correct payments, both private and public

**Comment by AugustoL** [comment]
I think is being checked right now on the property based tests, @nberger should we close it?

**Comment by nberger** [comment]
If we wanted to fully test it, we should check that the `totalSupply` equals the tokens from purchases + 20% for the team + 5% for the foundation, I don't think we are checking that in the property-based test

**Comment by AugustoL** [comment]
You are right.
